set -g prefix C-a
set -g mode-keys vi
set -g @tpm-install 'I'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin '2kabhishek/tmux2k'

bind c new-window
bind w list-window
bind n next-window
bind p previous-window

bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind Space copy-mode

bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi k send -X cursor-up
bind -T copy-mode-vi j   send -X cursor-down
bind -T copy-mode-vi h   send -X cursor-left
bind -T copy-mode-vi l  send -X cursor-right

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi Space  if -F "#{selection_present}" { send -X clear-selection } { send -X begin-selection }
bind -T copy-mode-vi y      send -X copy-selection-no-clear
bind -T copy-mode-vi Enter  send -X copy-selection-and-cancel

bind r source-file ~/.tmux.conf
